/**
 * List of Moroccan cities for address/delivery forms.
 * Alphabetically sorted, French transliterations used where standard.
 * Total: 345 cities
 */
export const MOROCCAN_CITIES = [
  'Afourar',
  'Agadir',
  'Aghbala',
  'Agourai',
  'Ahfir',
  'Ain Bni Mathar',
  'Ain Cheggag',
  'Ain Dorij',
  'Ain Harrouda',
  'Ain Jemaa',
  'Ain Karma',
  'Ain Leuh',
  'Ain Taoujdat',
  'Ait Ali',
  'Ait Baha',
  'Ait Boubidmane',
  'Ait Daoud',
  'Ait Iaaza',
  'Ait Ishaq',
  'Ait Melloul',
  'Ait Ourir',
  'Akka',
  'Aklim',
  'Aknoul',
  'Al Aaroui',
  'Al Hoceima',
  'Alnif',
  'Amizmiz',
  'Anzi',
  'Aoufous',
  'Aoulouz',
  'Aourir',
  'Arbaoua',
  'Arfoud',
  'Arhbalou',
  'Asilah',
  'Assahrij',
  'Assa-Zag',
  'Assilah',
  'Azemmour',
  'Azilal',
  'Azrou',
  'Bab Berred',
  'Bab Taza',
  'Barrechid',
  'Ben Ahmed',
  'Ben Guerir',
  'Ben Sergao',
  'Ben Taïeb',
  'Beni Ansar',
  'Beni Bouayach',
  'Beni Chiker',
  'Beni Enzar',
  'Beni Mellal',
  'Beni Yakhlef',
  'Berkane',
  'Berrechid',
  'Bhalil',
  'Bin elouidane',
  'Biougra',
  'Bir Jdid',
  'Bni Drar',
  'Bni Hadifa',
  'Bni Tadjite',
  'Boujdour',
  'Boujniba',
  'Boulanouare',
  'Boulemane',
  'Boumalne-Dades',
  'Bouskoura',
  'Bouznika',
  'Bradia',
  'Brikcha',
  'Bzou',
  'Casablanca',
  'Chefchaouen',
  'Chichaoua',
  'Dakhla',
  'Dar Bel Hamri',
  'Dar Bouazza',
  'Dar Chaoui',
  'Dar El Kebdani',
  'Dar Gueddari',
  'Dar Ould Zidouh',
  'Dcheira El Jihadia',
  'Demnate',
  'Deroua',
  'Drargua',
  'Driouch',
  'El Aïoun Sidi Mellouk',
  'El Borouj',
  'El Gara',
  'El Hajeb',
  'El Hanchane',
  'El Jadida',
  'El Kelaa des Sraghna',
  'El Ksiba',
  'El Marsa',
  'El Menzel',
  'Erfoud',
  'Errachidia',
  'Es-Semara',
  'Essaouira',
  'Fam El Hisn',
  'Farkhana',
  'Fas',
  'Fes',
  'Figuig',
  'Fnideq',
  'Foum Jamaa',
  'Foum Zguid',
  'Fquih Ben Salah',
  'Ghafsai',
  'Gharb Chrarda Beni Hssen',
  'Ghouazi',
  'Goulmima',
  'Gourrama',
  'Grand Casablanca',
  'Guelmim',
  'Guercif',
  'Guigou',
  'Guisser',
  'Hadj Kaddour',
  'Haj Kaddour',
  'Harhoura',
  'Hattane',
  'Hrara',
  'Ifrane',
  'Igdamen',
  'Ighoud',
  'Ighrem',
  'Ijoukak',
  'Ikhlalene',
  'Imassine',
  'Imintanoute',
  'Imouzzer Kandar',
  'Imouzzer Marmoucha',
  'Imzouren',
  'Inezgane',
  'Issaguen',
  'Itzer',
  'Jamaat Shaim',
  'Jaâdar',
  'Jerada',
  'Jorf',
  'Jorf El Melha',
  'Jorf Lasfar',
  'Karia',
  'Karia Ba Mohamed',
  'Kasba Tadla',
  'Kassita',
  'Kattara',
  'Kehf Nsour',
  'Kelaat Mgouna',
  'Kénitra',
  'Kerrouchen',
  'Khemis Zemamra',
  'Khemisset',
  'Khenichet',
  'Khenifra',
  'Khouribga',
  'Ksar El Kebir',
  'Ksar es Seghir',
  'Laaounate',
  'Laayoune',
  'Lakhsas',
  'Lakhsass',
  'Lalla Mimouna',
  'Lalla Takerkoust',
  'Larache',
  'Loudaya',
  'Loulad',
  'Lqliaa',
  'Madagh',
  'Maâmora',
  'Marrakech',
  'Martil',
  'Massa',
  'Mechra Bel Ksiri',
  'Mehdya',
  'Mehdia',
  'Meknes',
  'Melloussa',
  'Midelt',
  'Midar',
  'Missour',
  'Mohammedia',
  'Moqrisset',
  'Moulay Abdallah',
  'Moulay Bouchta',
  'Moulay Bousselham',
  'Moulay Bouzerktoun',
  'Moulay Driss Zerhoun',
  'Moulay Idriss Zerhoun',
  'Moulay Yacoub',
  'Moussaoua',
  'Mrirt',
  'Nador',
  'Naima',
  'Nouaceur',
  'Ouad Laou',
  'Oualidia',
  'Ouaouizeght',
  'Ouarzazate',
  'Ouazzane',
  'Oued Amlil',
  'Oued Heimer',
  'Oued Ifrane',
  'Oued Laou',
  'Oued Rmel',
  'Oued Zem',
  'Oued-Zem',
  'Ouezzane',
  'Oujda',
  'Oujda-Angad',
  'Oulad Abbou',
  'Oulad Amrane',
  'Oulad Ayad',
  'Oulad Berhil',
  'Oulad Frej',
  'Oulad Ghadbane',
  'Oulad Mbarek',
  'Oulad Saïd',
  'Oulad Sidi Ben Daoud',
  'Oulad Tayeb',
  'Oulad Teïma',
  'Oulad Yaich',
  'Oulad Zbair',
  'Ouled Tayeb',
  'Oulmes',
  'Oulmès',
  'Ounagha',
  'Outat Oulad Al Haj',
  'Ouzoud',
  'Point Cires',
  'Rabat',
  'Ras El Ain',
  'Ras El Ma',
  'Reggada',
  'Rehamna',
  'Ribat Al Khayr',
  'Rissani',
  'Rommani',
  'Sabaa Aiyoun',
  'Safi',
  'Sahel',
  'Saïdia',
  'Salé',
  'Seddina',
  'Sebt El Guerdane',
  'Sebt Gzoula',
  'Sebt Jahjouh',
  'Sebt Ouled Nemma',
  'Sefrou',
  'Selouane',
  'Settat',
  'Setti Fatma',
  'Sidi Abdallah Ghiat',
  'Sidi Addi',
  'Sidi Ahmed',
  'Sidi Ali Ban Hamdouche',
  'Sidi Allal El Bahraoui',
  'Sidi Allal Tazi',
  'Sidi Bennour',
  'Sidi Bou Othmane',
  'Sidi Boubker',
  'Sidi Bouknadel',
  'Sidi Bouzid',
  'Sidi Ifni',
  'Sidi Jaber',
  'Sidi Kacem',
  'Sidi Lamine',
  'Sidi Lyamani',
  'Sidi Mohamed ben Abdallah el-Raisuni',
  'Sidi Rahhal',
  'Sidi Rahhal Chataï',
  'Sidi Slimane',
  'Sidi Slimane Echcharaa',
  'Sidi Smaïl',
  'Sidi Smail',
  'Sidi Taibi',
  'Sidi Yahia El Gharb',
  'Sidi Yahya Zaer',
  'Skhirat',
  'Skhour Rehamna',
  'Smimou',
  'Soualem',
  'Souk El Arbaa',
  'Souk Sebt Oulad Nemma',
  "Souq Larb'a al Gharb",
  'Sour El Ghozlane',
  'Sraghna',
  'Stehat',
  'Tabounte',
  'Tafajight',
  'Tafetachte',
  'Tafraout',
  'Taghjijt',
  'Tahannaout',
  'Tahla',
  'Tala Youssef',
  'Talssint',
  'Tamanar',
  'Tamansourt',
  'Tamellalt',
  'Tamezmout',
  'Tameslouht',
  'Tamesna',
  'Tamraght',
  'Tan-Tan',
  'Tanger',
  'Tanant',
  'Tanoute',
  'Taounate',
  'Taourirt',
  'Tarfaya',
  'Targuist',
  'Taroudant',
  'Tata',
  'Taza',
  'Taznakht',
  'Telouet',
  'Temara',
  'Tetouan',
  'Thar Es-Souk',
  'Tiddas',
  'Tiflet',
  'Tifnit',
  'Tighassaline',
  'Tighza',
  'Tinghir',
  'Tirhanimine',
  'Tissa',
  'Tit Mellil',
  'Tiznit',
  'Tiztoutine',
  'Toulal',
  'Touima',
  'Touissit',
  'Toundoute',
  'Youssoufia',
  'Zag',
  'Zagora',
  'Zaïda',
  'Zaio',
  'Zaouia Ahansal',
  'Zaouiat Cheikh',
  'Zeghanghane',
  'Zerarda',
  'Zinat',
  'Zouagha Moulay Yacoub',
] as const;
